apiVersion: v2
name: pagopa-wisp-converter
description: A service that permits to handle nodoInviaRPT and nodoInviaCarrelloRPT request from WISP, interfacing them with GPD system
type: application
version: 0.208.0
appVersion: 0.3.5
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
